[theme]
inherit = basic
stylesheet = style.css
pygments_style = friendly
pygments_dark_style = monokai

[options]
tagline = Visual journalist/hacker covering AI
description = Kevin Schaul — Visual journalist/hacker covering AI
