baseurl: https://www.kschaul.com/
languageCode: en-us
title: Kevin Schaul
theme: "hugo-ivy"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$", "(^|/)renv$", "renv\\.lock$"]
footnotereturnlinkcontents: ↩
publishDir: public
timeZone: America/Chicago

permalinks:
  til: /til/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

taxonomies:
  tag: tags

menu:
  main:
    - name: "Contact"
      url: "/contact/"
      weight: 1
    - name: "Micro"
      url: "/link/"
      weight: 2
    - name: "Blog"
      url: "/post/"
      weight: 3
    - name: "Today I learned"
      url: "/til/"
      weight: 4


rssLimit: 10

params:
  description: "Visual journalist/hacker"
  footer: ""
  disable_highlight: true
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex", "js"]
  highlightjsTheme: "github"
  highlightjsVersion: "9.12.0"
  mainSections:
    - post
    - til
    - link

markup:
  goldmark:
    renderer:
      unsafe: true

