baseurl: https://www.kschaul.com/
languageCode: en-us
title: Kevin Schaul
theme: "hugo-ivy"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: ↩
publishDir: docs

permalinks:
  til: /til/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

taxonomies:
  tag: tags

menu:
  main:
    - name: "Contact"
      url: "/contact/"
      weight: 1
    - name: "Favorite links"
      url: "/favorites/"
      weight: 2
    - name: "Today I Learned"
      url: "/til/"
      weight: 3
    - name: "Archive"
      url: "/post/"
      weight: 4

rssLimit: 10

params:
  description: ""
  footer: ""
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex", "js"]
  highlightjsTheme: "github"
  highlightjsVersion: "9.12.0"

markup:
  goldmark:
    renderer:
      unsafe: true

