baseurl: https://www.kschaul.com/
languageCode: en-us
title: Kevin Schaul
theme: paper
publishDir: public
timeZone: America/Chicago

permalinks:
  til: /til/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

taxonomies:
  tag: tags

menu:
  main:
    - name: "About"
      url: "/contact/"
      weight: 1
    - name: "LLM evals"
      url: "https://kschaul.com/llm-evals/"
      weight: 2
    - name: "Follow"
      url: "/follow/"
      weight: 3

rssLimit: 10
paginate: 10

params:
  description: "Visual journalist/hacker covering AI"
  dateFormat: "Jan. 1, 2006"
  color: "gray"
  # github: "kevinschaul"
  # mastodon: "https://mastodon.social/@kevinschaul"
  # bluesky: "kevinschaul.bsky.social"
  # rss: true
  monoDarkIcon: true

markup:
  goldmark:
    renderer:
      unsafe: true

