baseurl: /
languageCode: en-us
title: Kevin Schaul
theme: "hugo-ivy"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩

permalinks:
  til: /til/:year/:month/:day/:slug/
  archive: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "Contact"
      url: "/contact/"
      weight: 1
    - name: "Favorite links"
      url: "/favorites/"
      weight: 2
    - name: "Today I Learned"
      url: "/til/"
      weight: 3
    - name: "Posts"
      url: "/post/"
      weight: 4

params:
  description: ""
  footer: ""
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"
  highlightjsVersion: "9.12.0"

markup:
  goldmark:
    renderer:
      unsafe: true
