baseurl: https://www.kschaul.com/
languageCode: en-us
title: Kevin Schaul
theme: paper
publishDir: public
timeZone: America/Chicago

permalinks:
  til: /til/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

taxonomies:
  tag: tags

menu:
  main:
    - name: "Contact"
      url: "/contact/"
      weight: 1
    - name: "Micro"
      url: "/link/"
      weight: 2
    - name: "Blog"
      url: "/post/"
      weight: 3
    - name: "Today I learned"
      url: "/til/"
      weight: 4

rssLimit: 10
paginate: 20

params:
  description: "Visual journalist/hacker"
  dateFormat: "Jan. 1, 2006"
  color: "gray"
  github: "kevinschaul"
  mastodon: "https://mastodon.social/@kevinschaul"
  bluesky: "kevinschaul.bsky.social"
  rss: true
  monoDarkIcon: true

markup:
  goldmark:
    renderer:
      unsafe: true

