---
date: 2011-05-13 13:58:32+00:00
layout: post
slug: 2011-05-13-whats-in-a-web-app
title: "What's in a web app?"
---

I've always wondered but have never been in a position to make the call between native or web apps. For the mobile redesign of [mndaily.com](http://mndaily.com), we had to make this decision. And we went with a web app. Here's why:

**It's stupid simple with the right tools.**

With mobile frameworks coming out weekly, it's too easy to get your web app to look and perform like a native app. I'm no [jquery mobile](http://jquerymobile.com/) expert, but I had a working version up and running in two hours. Also worth a look: [Sencha Touch](http://www.sencha.com/products/touch/demos/). It's a less-popular of programming (Ext.js), but custom layouts are a breeze.

**Users won't know the difference.**

Again, these frameworks do this all for you. Users care about looks, speed, and functionality, and sadly in that order. Make it look pretty and run smoothly, and you just about have a winner. Add the features, and you're golden.

**One code base.**

Best reason right here. One web app works on many, many platforms. Depending on the framework you choose, it'll likely work great on iOS, Android, WebOS, Blackberry OS (including the QNX-based tablet OS). This means much easier development, and in turn, a larger audience. And if you want to be in the respective app markets, [Phonegap](http://www.phonegap.com/) can make it happen with minimal work. For news organizations, and for many other companies, I don't see the logic in going native and abandoning half of the market. [The Daily](http://www.thedaily.com/) is a [prime example](http://www.businessinsider.com/the-daily-lost-10-million-in-its-first-quarter-2011-5) of this. Why limit yourself when the benefits are so minimal?

**You won't miss anything.**

Name something that a web app can't achieve, and I'll rethink this whole post. They can get the user's location, store data for offline use, load new pages without a browser refresh, whatever special features you need. If you're doing a 3D game, go native. Otherwise, and especially for news organizations' apps, web apps provide everything you need.

**No app store fuss.**

Have an update ready? Upload it, and it's live. Don't even worry about poorly-worded, loosely-enforced rules. Can you say that about other app markets?

"App" is a buzzword, but the only app that will matter is the browser. Mobile is imitating the desktop environment; we've realized that for most, [a browser is (almost) all we need](http://www.google.com/chromebook/).

